spring.application.name=Health_Web
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

#oracle db설정
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=MYWOO
spring.datasource.password=AUDDN25800

#mybatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:ymw/web/mybatis/*.xml
mybatis.type-aliases-package=ymw.web.dto

#/upload 로 요청이 들어오면 resource.path에서 찾기 
resource.path=file:///C:/resource/
upload.path=/upload/**

#이미지 파일 업로드 위치
resource=C:/resource

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB