spring.application.name=Health_Web
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

#oracle db설정
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=MYWOO
spring.datasource.password=AUDDN25800

#mybatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:ymw/web/mybatis/*.xml
mybatis.type-aliases-package=ymw.web.dto